# Cloudflare Pages Configuration for MMC-MMS
# Medical Committee Management System
# Updated: 2025-10-24

name = "2027"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# KV Namespaces - All properly bound
[[kv_namespaces]]
binding = "KV_CACHE"
id = "1d3d4e6c12174b7797b356234794e7e5"

[[kv_namespaces]]
binding = "KV_ADMIN"
id = "e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3"

[[kv_namespaces]]
binding = "KV_PINS"
id = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"

[[kv_namespaces]]
binding = "KV_QUEUES"
id = "f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6"

[[kv_namespaces]]
binding = "KV_EVENTS"
id = "c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6"

[[kv_namespaces]]
binding = "KV_LOCKS"
id = "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6"

# R2 Bucket for Reports and Backups
[[r2_buckets]]
binding = "R2_BUCKET_REPORTS"
bucket_name = "mmc-reports"

# Durable Objects for Mutex and Broadcast
[[durable_objects.bindings]]
name = "DO_ROUTER"
class_name = "RouterDO"
script_name = "2027"

# Environment Variables
[vars]
TIMEZONE = "Asia/Qatar"
JWT_SECRET = "ff8d89d5d4c3df95e47..."  # Keep existing
PIN_SECRET = "6a1f1a07787035f332..."  # Keep existing
NOTIFY_KEY = "https://notify.mmc-m..."  # Keep existing

# CRON Triggers - Critical for system operation
[triggers]
crons = [
  "0 0 * * *",      # Daily PIN reset at 00:00
  "*/1 * * * *",    # Notify poller every minute
  "59 23 * * *"     # Daily report at 23:59
]

# Build configuration
[build]
command = "echo 'No build needed for static site'"

# Custom domains
[[routes]]
pattern = "www.mmc-mms.com/*"
custom_domain = true

[[routes]]
pattern = "mmc-mms.com/*"
custom_domain = true

# Compatibility flags
[compatibility_flags]
nodejs_compat = true

