#!/usr/bin/env node
// طباعة QR في الطرفية باستخدام حزمة qrcode
// Generated by Copilot
import fs from 'node:fs'
import path from 'node:path'

async function main() {
  const args = process.argv.slice(2)
  const a0 = args[0]
  const publicFile = args[1] || path.join('logs','public_url.txt')
  let url = ''
  if (a0 && /^https?:\/\//i.test(a0)) {
    url = a0.trim()
  } else if (a0 && fs.existsSync(a0)) {
    url = fs.readFileSync(a0, 'utf8').trim()
  } else {
    try {
      if (fs.existsSync(publicFile)) {
        url = fs.readFileSync(publicFile, 'utf8').trim()
      }
    } catch {}
  }
  if (!url) {
    url = process.env.CF_URL || process.env.SITE_URL || 'https://mmc-mms.com'
  }
  // dynamic import to be ESM-compatible
  const QR = await import('qrcode')
  const str = await QR.toString(url, { type: 'terminal', small: true })
  console.log(`[qr] URL = ${url}`)
  console.log(str)
}

main().catch(err => { console.error(err); process.exit(1) })
