param(
  [string]$TaskPrefix = 'MMS'
)

# Generated by Copilot
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module ScheduledTasks -ErrorAction Stop

foreach ($name in @("$TaskPrefix-Server", "$TaskPrefix-Cloudflare")) {
  if (Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $name -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "[tasks] Removed: $name"
  }
}

Write-Host '[tasks] Done.'
