# ==============================================
# Auto PowerShell 7 Self-Fix Launcher
# يُضيف حارس تشغيل pwsh لكل سكربت داخل مجلد tools
# ==============================================

# 1) التحويل التلقائي إلى PowerShell 7 إن لم نكن عليه
if ($PSVersionTable.PSVersion.Major -lt 7) {
    Write-Host "[AUTO] PowerShell 7 not detected. Attempting relaunch via pwsh..." -ForegroundColor Yellow
    $scriptPath = $PSCommandPath
    $pwshPath = $null
    try { $pwshPath = (Get-Command pwsh -ErrorAction SilentlyContinue).Source } catch {}

    if (-not $pwshPath) {
        Write-Host "[AUTO] pwsh not found. You need to install PowerShell 7 manually (https://aka.ms/PowerShell)." -ForegroundColor Red
        Write-Host "[AUTO] Skipping patch phase; please re-run after installing pwsh." -ForegroundColor Red
        exit 1
    }
    Start-Process -FilePath $pwshPath -ArgumentList "-ExecutionPolicy Bypass -File `"$scriptPath`"" -WindowStyle Hidden
    exit
}

Write-Host "[AUTO] Running under PowerShell $($PSVersionTable.PSVersion.ToString())" -ForegroundColor Green

# 2) جمع السكربتات المستهدفة
$toolsRoot = $PSScriptRoot
$scriptFiles = Get-ChildItem -Path $toolsRoot -Filter '*.ps1' -Recurse | Where-Object { $_.FullName -ne $PSCommandPath }

# 3) الحارس القياسي
$guard = @"
if (
    $PSVersionTable.PSVersion.Major -lt 7
) {
    Write-Host '[AUTO] Relaunching under pwsh...' -ForegroundColor Yellow
    $pw = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
    if (-not $pw) { Write-Host '[AUTO] pwsh not installed. Install from https://aka.ms/PowerShell' -ForegroundColor Red; exit 1 }
    Start-Process -FilePath $pw -ArgumentList "-ExecutionPolicy Bypass -File `"$PSCommandPath`"" -WindowStyle Hidden
    exit
}
"@

# 4) تطبيق الحارس على الملفات غير المحمية
$patched = 0
foreach ($f in $scriptFiles) {
    $raw = Get-Content $f.FullName -Raw -ErrorAction SilentlyContinue
    if ($raw -match 'Relaunching under pwsh' -or $raw -match 'PSVersionTable') { continue }
    Set-Content -Path $f.FullName -Value ($guard + "`r`n" + $raw) -Encoding UTF8
    $patched++
    Write-Host "[AUTO] Patched: $($f.Name)" -ForegroundColor Gray
}

Write-Host "[AUTO] Patch complete. Patched files: $patched" -ForegroundColor Cyan
Write-Host "[AUTO] All future tool scripts will self-upgrade to pwsh when possible." -ForegroundColor Green

# Generated by Copilot
