Param(
  [string]$LogDir = "$PSScriptRoot\..\logs",
  [string]$ApiOrigin = "https://api.mmc-mms.com",
  [string]$SiteOrigin = "https://mmc-mms.com"
)

$ErrorActionPreference = 'SilentlyContinue'
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
$ts = Get-Date -Format 'yyyyMMdd_HHmm'
$report = Join-Path $LogDir "health-report-$ts.txt"

"Checking health at $(Get-Date)" | Out-File $report -Encoding utf8

try {
  $env:API_ORIGIN = $ApiOrigin
  $env:SITE_ORIGIN = $SiteOrigin
  node "$PSScriptRoot\..\infra\generate-health-status.js" | Tee-Object -FilePath $report -Append | Out-Null
} catch {
  "Error running generate-health-status.js: $_" | Out-File $report -Append
}

$content = Get-Content $report -Raw
if ($content -match '❌') {
  # إعادة تشغيل الخدمات ذات الصلة إذا كانت متوفرة
  Try { Restart-Service -Name "cloudflared" -Force -ErrorAction SilentlyContinue } Catch {}
  Try { Restart-Service -Name "node" -Force -ErrorAction SilentlyContinue } Catch {}
  "♻️ Restarted services at $(Get-Date)" | Out-File $report -Append
}

# Generated by Copilot