param(
  [string]$ProjectDir = "infra",
  [string]$ApiOrigin = "https://api.mmc-mms.com",
  [string]$WorkerDevOrigin = ""
)

Write-Host "Running health status generator..." -ForegroundColor Cyan

Push-Location $ProjectDir
if ($WorkerDevOrigin) {
  $env:WORKER_DEV_ORIGIN = $WorkerDevOrigin
}
$env:API_ORIGIN = $ApiOrigin

node generate-health-status.js
$code = $LASTEXITCODE
Pop-Location

if ($code -ne 0) {
  Write-Error "Health check failed (exit $code)."
  exit $code
}

Write-Host "Health OK." -ForegroundColor Green

# Generated by Copilot
