# Requires: Node.js, npm, and wrangler installed (we use npx wrangler). Run from repo root.
param(
  [string]$ProjectDir = "infra/worker-api"
)

Write-Host "Setting Cloudflare Worker secrets and variables..." -ForegroundColor Cyan

if (-not (Test-Path $ProjectDir)) {
  Write-Error "Project directory not found: $ProjectDir"; exit 1
}

Push-Location $ProjectDir

function Set-WorkerSecret($name, $value) {
  if (-not $value) { return }
  Write-Host "-> Setting secret $name" -ForegroundColor Yellow
  $pinfo = New-Object System.Diagnostics.ProcessStartInfo
  $pinfo.FileName = "npx"
  $pinfo.Arguments = "wrangler secret put $name"
  $pinfo.RedirectStandardInput = $true
  $pinfo.RedirectStandardOutput = $false
  $pinfo.RedirectStandardError = $false
  $pinfo.UseShellExecute = $false
  $p = New-Object System.Diagnostics.Process
  $p.StartInfo = $pinfo
  $null = $p.Start()
  $p.StandardInput.WriteLine($value)
  $p.StandardInput.Close()
  $p.WaitForExit()
  if ($p.ExitCode -ne 0) { Write-Error "Failed to set secret $name"; Pop-Location; exit $p.ExitCode }
}

function Set-WorkerVar([string]$name, [string]$value) {
  if (-not $value) { return }
  Write-Host "-> Setting var $name=$value" -ForegroundColor Yellow
  # Wrangler v4 supports vars via 'wrangler kv:namespace ...' for KV and 'wrangler deploy --var name=value'
  # Here we'll write a .vars.local for local dev and advise setting in wrangler.toml for non-secret vars.
  $varsFile = ".vars.local"
  if (-not (Test-Path $varsFile)) { New-Item -Path $varsFile -ItemType File -Force | Out-Null }
  $content = Get-Content $varsFile -Raw -ErrorAction SilentlyContinue
  $lines = @()
  if ($content) { $lines = $content -split "`n" }
  $lines = $lines | Where-Object {$_ -and ($_ -notmatch "^$name=")}
  $lines += "$name=$value"
  Set-Content -Path $varsFile -Value ($lines -join "`n") -Encoding UTF8
}

$BACKEND_ORIGIN = Read-Host "Enter BACKEND_ORIGIN (e.g., https://app.mmc-mms.com)"
$ADMIN_BASIC_USER = Read-Host "Enter ADMIN_BASIC_USER (optional)"
$ADMIN_BASIC_PASS = Read-Host "Enter ADMIN_BASIC_PASS (optional)"
$JWT_SECRET = Read-Host "Enter JWT_SECRET (optional)"
$SITE_ORIGIN = Read-Host "Enter SITE_ORIGIN (default https://mmc-mms.com)"
if (-not $SITE_ORIGIN) { $SITE_ORIGIN = "https://mmc-mms.com" }

Set-WorkerSecret -name "BACKEND_ORIGIN" -value $BACKEND_ORIGIN
if ($ADMIN_BASIC_USER) { Set-WorkerSecret -name "ADMIN_BASIC_USER" -value $ADMIN_BASIC_USER }
if ($ADMIN_BASIC_PASS) { Set-WorkerSecret -name "ADMIN_BASIC_PASS" -value $ADMIN_BASIC_PASS }
if ($JWT_SECRET) { Set-WorkerSecret -name "JWT_SECRET" -value $JWT_SECRET }

Set-WorkerVar -name "SITE_ORIGIN" -value $SITE_ORIGIN

Write-Host "All set. You can now deploy the Worker (npx wrangler deploy)." -ForegroundColor Green

Pop-Location

# Generated by Copilot
