-- DB-MIGRATION.sql — C6-FIX: التحقق من وجود RPC get_next_queue_number
-- تاريخ: 2026-02-23

-- ملاحظة: RPC get_next_queue_number موجودة بالفعل في Supabase
-- (تم التحقق من استخدامها في api/v1.js السطر 673)
-- هذا الملف يوثق البنية المتوقعة للدالة للمرجعية فقط

-- البنية المتوقعة لـ RPC get_next_queue_number:
-- CREATE OR REPLACE FUNCTION get_next_queue_number(
--   p_patient_id TEXT,
--   p_clinic_id TEXT,
--   p_exam_type TEXT
-- )
-- RETURNS INTEGER
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--   v_today DATE := CURRENT_DATE;
--   v_next_number INTEGER;
-- BEGIN
--   -- قفل ذري على مستوى العيادة واليوم
--   SELECT COALESCE(MAX(display_number), 0) + 1
--   INTO v_next_number
--   FROM unified_queue
--   WHERE clinic_id = p_clinic_id
--     AND DATE(entered_at) = v_today
--   FOR UPDATE;
--   
--   RETURN v_next_number;
-- END;
-- $$;

-- إذا لم تكن الدالة موجودة، يمكن إنشاؤها بالكود أعلاه
-- الإصلاح C6 يستخدم هذه الدالة تلقائياً مع fallback آمن
