name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Quick repo sanity
        run: |
          echo "Tree top-level:" && ls -la || true
          if [ -f MANUS_WORK_LOG.md ]; then echo "Found MANUS_WORK_LOG.md"; fi
          if [ -f vercel.json ]; then echo "Found vercel.json"; fi

      - name: Detect Node project
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "has_node=true" >> $GITHUB_OUTPUT
          else
            echo "has_node=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.detect.outputs.has_node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        if: steps.detect.outputs.has_node == 'true'
        run: npm ci --ignore-scripts

      - name: Lint (skip if no script)
        if: steps.detect.outputs.has_node == 'true'
        run: npm run lint --if-present

      - name: Typecheck (skip if no script)
        if: steps.detect.outputs.has_node == 'true'
        run: npm run typecheck --if-present

      - name: Build
        if: steps.detect.outputs.has_node == 'true'
        run: npm run build --if-present

      - name: Vercel config sanity
        run: |
          if [ -f vercel.json ]; then
            cat vercel.json
          else
            echo "No vercel.json (ok if not using Vercel)."
          fi
