name: Guard UI

on: [pull_request]

jobs:
  block-ui-edits:
    if: "!contains(github.event.pull_request.labels.*.name, 'ui:allowed')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block UI path changes unless labeled
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          if echo "$CHANGED" | egrep -q '^(index\.html|public/|src/)'; then
            echo 'UI paths changed without label ui:allowed' && exit 1
          else
            echo 'OK'
          fi
