name: Frontend Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read
  contents: read

jobs:
  guard:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const {owner, repo} = context.repo;
            const files = await github.paginate(github.rest.pulls.listFiles, {owner, repo, pull_number: pr.number, per_page: 100});
            const allowed = [
              /^backend//,
              /^extensions//,
              /^\.github//,
              /^README.md$/
            ];
            const forbidden = [
              /^index.html$/,
              /^package.json$/,
              /^assets//,
              /^public//,
              /^src//
            ];
            const changed = files.map(f => f.filename);
            const blocked = changed.filter(path => forbidden.some(rx => rx.test(path)));
            if (blocked.length) {
              core.setFailed('Blocked UI files modified: ' + blocked.join(', '));
              return;
            }
            const notAllowed = changed.filter(path => !allowed.some(rx => rx.test(path)) && !forbidden.some(rx => rx.test(path)));
            if (notAllowed.length) {
              core.warning('Files outside allowed areas: ' + notAllowed.join(', ') + '\nApprove explicitly if intended.');
            }
            core.info('Guard passed.');
