name: Guard - Allowed Paths Only
on: [pull_request]
permissions: { contents: read }
jobs:
  scope:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v45
        id: files
      - name: Enforce allowed paths
        run: |
          ALLOWED='^(src/core/event-bus\.js|vite\.config\.js|\.env\.local\.example|scripts/test/.*\.cjs|\.github/workflows/.*\.yml|\.github/pull_request_template\.md|\.github/copilot-instructions\.md|docs/.*|scripts/maintenance/.*\.cjs|archive/unused/.*|package\.json|package-lock\.json|\.gitignore)$'
          FAIL=0
          for f in ${{ steps.files.outputs.all_changed_files }}; do
            if echo "$f" | grep -Eq "$ALLOWED"; then
              echo "OK: $f"
            else
              echo "::error::File not allowed in this PR: $f"
              FAIL=1
            fi
          done
          exit $FAIL
