name: Guard - No UI Changes
on: [pull_request]
permissions: { contents: read }
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Get changed files
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }}... > changed.txt
          echo "Changed files:"; cat changed.txt
          BLOCKED_REGEX='^(src/styles/|src/components/ui/|public/|src/assets/)'
          if grep -E "$BLOCKED_REGEX" changed.txt; then
            echo "::error::UI/Assets changes are not allowed in this PR."
            exit 1
          fi
          echo "OK"
