name: Health - FE & API
on:
  workflow_dispatch:
    inputs:
      url: { description: "Deploy URL", required: false, default: "" }
  pull_request:
    types: [opened, synchronize, reopened]
permissions: { contents: read, issues: write }
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run health-check (Preview or Provided URL)
        env:
          DEPLOY_URL: ${{ github.event.inputs.url != '' && github.event.inputs.url || secrets.GH_PATH }}
          STRICT: "true"
          ENDPOINTS: "/api/v1/status"
        run: |
          if [ -z "$DEPLOY_URL" ]; then
            echo "::warning::DEPLOY_URL/GH_PATH not set; running local dev check."
            echo "Please set secrets.GH_PATH or pass url input."
            exit 78  # neutral
          fi
          node scripts/test/vercel-health-check.cjs
