# snippet: use GITHUB_TOKEN (recommended)
- name: Create success issue as fallback notification
  if: ${{ success() && steps.send_email.outcome != 'success' }}
  uses: actions/github-script@v6
  with:
    # use the runner-provided token (safer) — do NOT point to your custom PAT here
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const title = 'نجاح النشر — تم إنجاز المشروع 100%';
      const repoLine = '- Repository: ' + context.repo.owner + '/' + context.repo.repo;
      const branchLine = '- Branch: main';
      const deployed = process.env.DEPLOY_URL || github.event.inputs.url || 'لم يتم توفير DEPLOY_URL';
      const deployedLine = '- Deployed URL: ' + deployed;
      const body = '**تم إنجاز المشروع بنجاح بنسبة 100%**\n\n' +
                   repoLine + '\n' +
                   branchLine + '\n' +
                   deployedLine + '\n\n' +
                   'جميع الفحوصات التشغيلية والـAPI والميزات تعمل بدون أخطاء.';
      await github.rest.issues.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        title,
        body,
        labels: ['deployment-success']
      });
