name: Production Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://mmc-mms.com
      API_BASE: https://mmc-mms.com/api/v1
    steps:
      - name: Front
        run: curl -fsSL -o /dev/null -w '%{http_code} %{time_total}\n' "$BASE_URL" || echo "Failed with exit code $?"
      - name: Healthz
        run: curl -fsSL -o /dev/null -w '%{http_code} %{time_total}\n' "$API_BASE/healthz" || echo "Failed with exit code $?"
      - name: Ping
        run: curl -fsSL -o /dev/null -w '%{http_code} %{time_total}\n' "$API_BASE/ping?x=1" || echo "Failed with exit code $?"
