name: Test GITHUB_TOKEN (one-time)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Optional PR number to comment on instead of creating an Issue"
        required: false
        default: ""

permissions:
  contents: read
  issues: write

jobs:
  token-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Use GITHUB_TOKEN to create Issue or comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNum = core.getInput('pr_number') || '';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const actor = context.actor;
            const runId = process.env.GITHUB_RUN_ID;

            if (prNum && /^\d+$/.test(prNum)) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: Number(prNum),
                body: `✅ GITHUB_TOKEN smoke test: token can comment on PR #${prNum}.\nActor: ${actor} | Run: ${runId}`
              });
              core.info(`Commented successfully on PR #${prNum}.`);
            } else {
              const title = 'GITHUB_TOKEN smoke test';
              const body = [
                '**This issue confirms that the runner-provided GITHUB_TOKEN is valid and has write permissions in this repo.**',
                `- Actor: ${actor}`,
                `- Repo: ${owner}/${repo}`,
                `- Run: ${runId}`
              ].join('\n');

              await github.rest.issues.create({ owner, repo, title, body, labels: ['token-test'] });
              core.info('Created confirmation issue.');
            }

      - name: Summary
        run: |
          echo "GITHUB_TOKEN smoke test completed. Check the repository's Issues (or the target PR) for confirmation."
