name: URL Guard

on: [pull_request]

jobs:
  check-bad-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for duplicated Supabase path
        run: |
          if grep -RIn "/functions/v1/api/v1" src tools middleware infra 2>/dev/null; then
            echo '❌ Found duplicated /functions/v1/api/v1. Please use /functions/v1/<function>.'
            exit 1
          else
            echo '✅ No duplicated paths found.'
          fi
